import * as THREE from './assets/three.module.min.js';
const track=document.querySelector('.journey'), canvas=document.querySelector('#scene');
const intro=document.querySelector('.intro'), note=document.querySelector('.scene-note'), finish=document.querySelector('.finish'),cue=document.querySelector('.scroll-cue'),bar=document.querySelector('.progress i');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));const smooth=(a,b,v)=>{const t=clamp((v-a)/(b-a));return t*t*(3-2*t)};
let renderer,scene,camera,mesh,frame=0,current=0,target=0,last=0,loaded=false;
function position(){target=clamp((scrollY-track.offsetTop)/Math.max(1,track.offsetHeight-innerHeight));wake()}
function ui(p){intro.style.opacity=1-smooth(0,.2,p);intro.style.transform=`translateY(${-55*smooth(0,.24,p)}px)`;note.style.opacity=smooth(.23,.36,p)*(1-smooth(.51,.64,p));finish.style.opacity=smooth(.72,.9,p);const reveal=smooth(.68,.98,p);finish.style.transform=`translate(-50%,-50%) perspective(1000px) translateZ(${-240*(1-reveal)}px) rotateX(${9*(1-reveal)}deg)`;cue.style.opacity=1-smooth(0,.14,p);bar.style.transform=`scaleX(${p})`}
function draw(now){frame=0;const dt=last?Math.min((now-last)/1000,.05):.016;last=now;current+=(target-current)*(1-Math.exp(-dt*7));if(Math.abs(target-current)<.0001)current=target;ui(current);if(loaded){const p=smooth(0,.88,current),yaw=THREE.MathUtils.degToRad(-115-42*p);camera.fov=(innerWidth<700?79:66)-12*p;camera.position.set(Math.sin(yaw)*3*p,.05*p,Math.cos(yaw)*3*p);camera.lookAt(Math.sin(yaw)*40,-2.5+p,Math.cos(yaw)*40);camera.updateProjectionMatrix();renderer.render(scene,camera)}if(Math.abs(target-current)>.0001)wake();else last=0}
function wake(){if(!frame&&!reduced.matches)frame=requestAnimationFrame(draw)}
function resize(){if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;}position()}
if(!reduced.matches){try{renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:true,powerPreference:'low-power'});renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.1,150);const geometry=new THREE.SphereGeometry(45,64,32);geometry.scale(-1,1,1);new THREE.TextureLoader().load('assets/loft.png',texture=>{texture.colorSpace=THREE.SRGBColorSpace;mesh=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({map:texture}));mesh.rotation.y=-Math.PI/2;scene.add(mesh);loaded=true;document.body.classList.add('ready');resize()},undefined,()=>{canvas.hidden=true});resize()}catch(error){canvas.hidden=true}addEventListener('scroll',position,{passive:true});addEventListener('resize',resize,{passive:true});addEventListener('pageshow',position);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0;last=0}else position()});}
reduced.addEventListener('change',()=>location.reload());
