'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='paulqc:'+CONFIG.id;
let groups=[],ids=[],labels={},active=0,ready=false;
let state={answers:{},notes:{},overall:'',name:'',reviewerId:''};
$('#send').disabled=true;
function verdict(id){const v=state.answers[id]||'-';return (state.notes[id]||'').trim()&&v!=='X'?'F':v}
function encode(){return ids.map(verdict).join('')}
function setStatus(s){$('#status').textContent=s}
function save(){try{localStorage.setItem(key,JSON.stringify(state));const p=new URLSearchParams({g:groups[active].id,r:encode()});history.replaceState(null,'','#'+p);setStatus('Draft saved on this device.')}catch(e){setStatus('Browser saving unavailable. Use Copy answers.')}updateProgress()}
function count(g){return [...g.kept.map(k=>k.id),g.gridId].filter(id=>verdict(id)!=='-').length}
function updateProgress(){if(!ready)return;$('#progress').textContent=ids.filter(id=>verdict(id)!=='-').length+' of '+ids.length+' decisions';document.querySelectorAll('.family-button').forEach((b,i)=>b.querySelector('.done').textContent=count(groups[i])+'/'+(groups[i].kept.length+1))}
function controls(id,label){return `<div class="controls" data-id="${esc(id)}" role="group" aria-label="Decision for ${esc(label)}">${[['K','Keep'],['F','Flag'],['X','Kill']].map(([v,t])=>`<button type="button" data-verdict="${v}" aria-pressed="${verdict(id)===v}">${t}</button>`).join('')}</div><textarea class="item-note ${(state.notes[id]||'').trim()?'has-note':''}" data-note="${esc(id)}" aria-label="Notes for ${esc(label)}" placeholder="Notes">${esc(state.notes[id]||'')}</textarea>`}
function renderNav(){ $('#families').innerHTML=groups.map((g,i)=>`<button type="button" class="family-button" data-family="${i}" aria-current="${i===active}"><span class="num">${g.code}</span><span class="nav-text">${esc(g.name)}<small>${g.kept.length} poster${g.kept.length===1?'':'s'} + grid</small></span><span class="done">${count(g)}/${g.kept.length+1}</span></button>`).join('') }
function render(){const g=groups[active];renderNav();$('#family').innerHTML=`<div class="family-heading"><div><p class="eyebrow">DIRECTION ${g.code} / ${String(groups.length).padStart(2,'0')}</p><h2>${esc(g.name)}</h2></div><a href="#grid-view">See the grid ↓</a></div><div class="posters ${g.kept.length===1?'single':''}" style="--cols:${g.kept.length}">${g.kept.map(k=>`<article class="poster"><a class="image-link" href="${esc(k.src)}" target="_blank" rel="noopener" aria-label="Open ${esc(k.label)} at full resolution"><img loading="eager" decoding="async" src="${esc(k.preview)}" width="${k.width}" height="${k.height}" alt="${esc(g.name+' — '+k.label+' poster')}"></a><div class="image-label"><span>${esc(k.label)}</span><a href="${esc(k.src)}" download>Download PNG ↗</a></div>${controls(k.id,g.name+' / '+k.label)}</article>`).join('')}</div><section class="grid-section" id="grid-view"><div class="section-title"><h3>The grid</h3><span>${g.kept.length} design${g.kept.length===1?'':'s'} in a 9-tile feed</span></div><div class="grid-review"><div class="feed">${g.tiles.map(t=>`<a class="tile ${t.photo?'photo':''}" href="${esc(t.src)}" target="_blank" rel="noopener" aria-label="Open ${esc(t.label)}"><img loading="lazy" decoding="async" src="${esc(t.preview)}" alt="${esc(t.label)}"></a>`).join('')}</div><div class="grid-feedback"><h4>Grid direction</h4><p>Does this style feel consistent across the feed?</p>${controls(g.gridId,g.name+' / Grid')}<p class="fine">This is a layout example. The selected posters and original photos repeat to show the visual rhythm.</p><a href="${esc(g.gridImage)}" target="_blank" rel="noopener">Open full grid ↗</a><p class="fine">Event details are retained from the supplied artwork for design review.</p></div></div></section><div class="family-pager"><button type="button" data-step="-1" ${active===0?'disabled':''}>← Previous direction</button><button type="button" data-step="1" ${active===groups.length-1?'disabled':''}>Next direction →</button></div>`;updateProgress()}
function choose(n){active=Math.max(0,Math.min(groups.length-1,n));render();save();$('#review').scrollIntoView({block:'start',behavior:'instant'});$('#review').focus({preventScroll:true})}
document.addEventListener('click',e=>{const a=e.target.closest('a[href="#grid-view"],a[href="#feedback"],a[href="#review"]');if(!a)return;e.preventDefault();document.querySelector(a.getAttribute('href'))?.scrollIntoView({block:'start'})});
$('#families').addEventListener('click',e=>{let b=e.target.closest('[data-family]');if(b)choose(Number(b.dataset.family))});
$('#family').addEventListener('click',e=>{let step=e.target.closest('[data-step]');if(step){choose(active+Number(step.dataset.step));return}let b=e.target.closest('[data-verdict]');if(!b)return;const group=b.closest('[data-id]'),id=group.dataset.id;state.answers[id]=state.answers[id]===b.dataset.verdict?'-':b.dataset.verdict;save();group.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',verdict(id)===x.dataset.verdict))});
$('#family').addEventListener('input',e=>{const id=e.target.dataset.note;if(!id)return;state.notes[id]=e.target.value;e.target.classList.toggle('has-note',!!e.target.value.trim());save();e.target.previousElementSibling.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',verdict(id)===x.dataset.verdict))});
for(const f of ['overall','name'])$('#'+f).addEventListener('input',e=>{state[f]=e.target.value;if(ready)save()});
function answerText(){return [CONFIG.title,state.name.trim()||'Anonymous','',...ids.map(id=>labels[id]+': '+({K:'Keep',F:'Flag',X:'Kill'}[verdict(id)]||'Not reviewed')+(state.notes[id]?' | '+state.notes[id]:'')),'','Overall: '+state.overall,location.href].join('\n')}
$('#copy').addEventListener('click',async()=>{if(!ready)return;let text=answerText();try{await navigator.clipboard.writeText(text);setStatus('Answers copied.')}catch(e){$('#copy-fallback').hidden=false;$('#copy-fallback').value=text;$('#copy-fallback').focus();$('#copy-fallback').select();setStatus('Select and copy the answers in the text box.')}});
async function getStore(){if(CONFIG.store){let r=await fetch(CONFIG.store+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Could not read responses. Your draft is saved; please retry.');let d=await r.json();if(!Array.isArray(d.submissions))throw Error('Response store unavailable. Your draft is saved.');return d}let d=JSON.parse(localStorage.getItem(key+':submissions')||'{"submissions":[]}');if(!Array.isArray(d.submissions))throw Error('Saved responses could not be read.');return d}
$('#send').addEventListener('click',async()=>{if(!ready)return;$('#send').disabled=true;setStatus(CONFIG.store?'Sending answers…':'Saving answers…');try{const d=await getStore(),name=state.name.trim()||'Anonymous';const rec={name,ts:new Date().toISOString(),reviewerId:state.reviewerId,ids:[...ids],answers:encode(),notes:{...state.notes},overall:state.overall};d.submissions=d.submissions.filter(s=>s.reviewerId!==rec.reviewerId&&(!state.name.trim()||(s.name||'').trim().toLowerCase()!==name.toLowerCase()));d.submissions.push(rec);if(CONFIG.store){const r=await fetch(CONFIG.store,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw Error('Send failed. Please retry or copy your answers.')}else localStorage.setItem(key+':submissions',JSON.stringify(d));setStatus(CONFIG.store?'Answers sent. You can revise and send again.':'Answers saved locally.')}catch(e){setStatus(e.message||'Send failed. Your draft is saved.')}finally{$('#send').disabled=false}});
(async()=>{try{const r=await fetch('manifest.json');if(!r.ok)throw Error();const d=await r.json();groups=d.groups;for(const g of groups){for(const k of g.kept){ids.push(k.id);labels[k.id]=g.name+' / '+k.label}ids.push(g.gridId);labels[g.gridId]=g.name+' / Grid'}let stored=null;try{stored=JSON.parse(localStorage.getItem(key)||'null');if(stored)state={...state,...stored}}catch(e){}state.answers=state.answers||{};state.notes=state.notes||{};if(!state.reviewerId)state.reviewerId=crypto.randomUUID();const h=new URLSearchParams(location.hash.slice(1)),answer=h.get('r');if(answer&&/^[KFX-]+$/.test(answer)&&answer.length===ids.length&&(!stored||answer!==encode()))ids.forEach((id,i)=>state.answers[id]=answer[i]);const group=groups.findIndex(g=>g.id===h.get('g'));active=group<0?0:group;$('#overall').value=state.overall;$('#name').value=state.name;if(!CONFIG.store)$('#send').textContent='Save answers';ready=true;render();save();$('#send').disabled=false}catch(e){$('#family').innerHTML='<p class="notice">The review could not load. Please refresh the page.</p>';setStatus('Review unavailable. Please refresh.')}})();
