'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='paulqc:'+CONFIG.id;
let groups=[],ids=[],labels={},ready=false;
let state={answers:{},notes:{},overall:'',name:'',reviewerId:''};
$('#send').disabled=true;
function verdict(id){const v=state.answers[id]||'-';return (state.notes[id]||'').trim()&&v!=='X'?'F':v}
function encode(){return ids.map(verdict).join('')}
function setStatus(s){$('#status').textContent=s}
function save(){try{localStorage.setItem(key,JSON.stringify(state));const p=new URLSearchParams({r:encode()});history.replaceState(null,'','#'+p);setStatus('Draft saved.')}catch(e){setStatus('Browser saving unavailable. Use Copy answers.')}}
function controls(id,label){return `<div class="controls" data-id="${esc(id)}" role="group" aria-label="Decision for ${esc(label)}">${[['K','Keep'],['F','Flag'],['X','Kill']].map(([v,t])=>`<button type="button" data-verdict="${v}" aria-pressed="${verdict(id)===v}">${t}</button>`).join('')}</div><textarea class="item-note ${(state.notes[id]||'').trim()?'has-note':''}" data-note="${esc(id)}" aria-label="Notes for ${esc(label)}" placeholder="Notes">${esc(state.notes[id]||'')}</textarea>`}
function render(){
const overview=`<section class="overview" id="overview"><h2 class="set-heading">00 — All posters</h2><div class="overview-posters">${groups.map(g=>g.kept.map(k=>`<figure class="overview-poster"><a href="${esc(k.src)}" target="_blank" rel="noopener" aria-label="Open ${esc(g.displayCode+' '+k.label)}"><img src="${esc(k.preview)}" width="${k.width}" height="${k.height}" alt="${esc(g.displayCode+' — '+k.label)}" loading="eager" decoding="async"></a><figcaption><a href="#set-${esc(g.id)}">${esc(g.displayCode==='New set'?'New':g.displayCode)} · ${esc(k.label)}</a></figcaption></figure>`).join('')).join('')}</div></section>`;
$('#family').innerHTML=overview+groups.map((g,n)=>{
const heading=g.displayCode;
return `<section class="collection" id="set-${esc(g.id)}" data-group="${esc(g.id)}"><h2 class="set-heading">${esc(heading)}</h2><div class="posters ${g.kept.length===1?'single':''}" style="--cols:${g.kept.length}">${g.kept.map(k=>`<figure class="poster"><a href="${esc(k.src)}" target="_blank" rel="noopener" aria-label="Open ${esc(heading+' '+k.label)}"><img loading="lazy" decoding="async" src="${esc(k.preview)}" width="${k.width}" height="${k.height}" alt="${esc(heading+' — '+k.label)}"></a><figcaption><span>${esc(k.label)}</span><a href="${esc(k.src)}" download>Download PNG ↗</a></figcaption>${controls(k.id,heading+' / '+k.label)}</figure>`).join('')}</div><div class="grid-section"><div class="grid-heading"><h3>${esc(heading)} grid example</h3><span>Repeated posters</span></div><div class="feed">${g.tiles.map(t=>`<a class="tile" data-poster="${esc(t.id)}" href="${esc(t.src)}" target="_blank" rel="noopener"><img loading="lazy" decoding="async" src="${esc(t.preview)}" alt="${esc(t.label)}"></a>`).join('')}</div><div class="grid-feedback">${controls(g.gridId,heading+' / Grid')}</div></div></section>`}).join('') }
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const target=document.getElementById(a.getAttribute('href').slice(1));if(!target)return;e.preventDefault();target.scrollIntoView({block:'start'})});
$('#family').addEventListener('click',e=>{let b=e.target.closest('[data-verdict]');if(!b)return;const group=b.closest('[data-id]'),id=group.dataset.id;state.answers[id]=state.answers[id]===b.dataset.verdict?'-':b.dataset.verdict;save();group.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',verdict(id)===x.dataset.verdict))});
$('#family').addEventListener('input',e=>{const id=e.target.dataset.note;if(!id)return;state.notes[id]=e.target.value;e.target.classList.toggle('has-note',!!e.target.value.trim());save();e.target.previousElementSibling.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',verdict(id)===x.dataset.verdict))});
for(const f of ['overall','name'])$('#'+f).addEventListener('input',e=>{state[f]=e.target.value;if(ready)save()});
function answerText(){return [CONFIG.title,state.name.trim()||'Anonymous','',...ids.map(id=>labels[id]+': '+({K:'Keep',F:'Flag',X:'Kill'}[verdict(id)]||'Not reviewed')+(state.notes[id]?' | '+state.notes[id]:'')),'','Overall: '+state.overall,location.href].join('\n')}
$('#copy').addEventListener('click',async()=>{if(!ready)return;let text=answerText();try{await navigator.clipboard.writeText(text);setStatus('Answers copied.')}catch(e){$('#copy-fallback').hidden=false;$('#copy-fallback').value=text;$('#copy-fallback').focus();$('#copy-fallback').select();setStatus('Select and copy the answers in the text box.')}});
async function getStore(){if(CONFIG.store){let r=await fetch(CONFIG.store+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Could not read responses. Your draft is saved; please retry.');let d=await r.json();if(!Array.isArray(d.submissions))throw Error('Response store unavailable. Your draft is saved.');return d}let d=JSON.parse(localStorage.getItem(key+':submissions')||'{"submissions":[]}');if(!Array.isArray(d.submissions))throw Error('Saved responses could not be read.');return d}
$('#send').addEventListener('click',async()=>{if(!ready)return;$('#send').disabled=true;setStatus(CONFIG.store?'Sending answers…':'Saving answers…');try{const d=await getStore(),name=state.name.trim()||'Anonymous';const rec={name,ts:new Date().toISOString(),reviewerId:state.reviewerId,ids:[...ids],answers:encode(),notes:{...state.notes},overall:state.overall};d.submissions=d.submissions.filter(s=>s.reviewerId!==rec.reviewerId&&(!state.name.trim()||(s.name||'').trim().toLowerCase()!==name.toLowerCase()));d.submissions.push(rec);if(CONFIG.store){const r=await fetch(CONFIG.store,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw Error('Send failed. Please retry or copy your answers.')}else localStorage.setItem(key+':submissions',JSON.stringify(d));setStatus(CONFIG.store?'Answers sent. You can revise and send again.':'Answers saved locally.')}catch(e){setStatus(e.message||'Send failed. Your draft is saved.')}finally{$('#send').disabled=false}});
(async()=>{try{const r=await fetch('manifest.json?v=3');if(!r.ok)throw Error();const d=await r.json();groups=d.groups;for(const g of groups){for(const k of g.kept){ids.push(k.id);labels[k.id]=g.displayCode+' / '+k.label}ids.push(g.gridId);labels[g.gridId]=g.displayCode+' / Grid'}let stored=null;try{stored=JSON.parse(localStorage.getItem(key)||'null');if(stored)state={...state,...stored}}catch(e){}state.answers=state.answers||{};state.notes=state.notes||{};if(!state.reviewerId)state.reviewerId=crypto.randomUUID();const h=new URLSearchParams(location.hash.slice(1)),answer=h.get('r');if(answer&&/^[KFX-]+$/.test(answer)&&answer.length===ids.length&&(!stored||answer!==encode()))ids.forEach((id,i)=>state.answers[id]=answer[i]);$('#overall').value=state.overall;$('#name').value=state.name;if(!CONFIG.store)$('#send').textContent='Save answers';ready=true;render();save();$('#send').disabled=false;const oldGroup=h.get('g');if(oldGroup&&groups.some(g=>g.id===oldGroup))document.getElementById('set-'+oldGroup)?.scrollIntoView({block:'start'})}catch(e){$('#family').innerHTML='<p class="notice">The review could not load. Please refresh the page.</p>';setStatus('Review unavailable. Please refresh.')}})();
