'use strict';
const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog=[],current=null;
const groups=[['BRAND','Brand'],['BRAND_FULL','Brand · full name'],['EVENT_DAY','Event day'],['EVENT_DATE','Date · full'],['EVENT_DATE_SHORT','Date · short'],['EVENT_TIME','Time'],['PRICE','Price']];
function defaultValue(key,defs){let value=defs['{{'+key+'}}']??defs['{{'+key+'_UPPER}}'];if(value===undefined)return null;if(key==='EVENT_DAY'||key==='PRICE')value=value.slice(0,1).toUpperCase()+value.slice(1).toLowerCase();if(key==='EVENT_DATE')value=value.toLowerCase().replace(/\b[a-z]/g,c=>c.toUpperCase());if(key==='EVENT_TIME')value=value.toLowerCase();return value}
function fillPrompt(){let text=current.template;for(let [token,original] of Object.entries(current.defaults)){let key=token.slice(2,-2),base=key.endsWith('_UPPER')?key.slice(0,-6):key;let input=q('[data-field="'+base+'"]');let value=input?input.value:original;if(key.endsWith('_UPPER'))value=value.toUpperCase();text=text.split(token).join(value)}q('#full-prompt').value=text;q('#prompt-status').textContent=''}
function render(){current=catalog.find(p=>p.id===q('#poster').value)||catalog[0];q('#poster').value=current.id;history.replaceState(null,'','#'+current.id);let fields=groups.map(([key,label])=>{let value=defaultValue(key,current.defaults);return value===null?'':'<label>'+esc(label)+'<input data-field="'+key+'" aria-label="'+esc(label)+'" value="'+esc(value)+'"></label>'}).join('');q('#chosen').innerHTML='<div class="prompt-head"><h2>'+esc(current.id)+' · '+esc(current.style)+'</h2><p>Upload '+(current.topic==='performance'?'one person photo for facial identity. The gym pose is generated.':'one normal gym/coaching photo. Keep its actual pose and clothing.')+'</p></div><div class="comparison"><figure><a href="'+esc(current.selected_image)+'" target="_blank" rel="noopener"><img src="'+esc(current.selected_preview)+'" alt="Selected '+esc(current.id)+'"></a><figcaption>Selected poster</figcaption></figure><figure><a href="'+esc(current.test_image)+'" target="_blank" rel="noopener"><img src="'+esc(current.test_preview)+'" width="'+current.width+'" height="'+current.height+'" alt="Photo and text test for '+esc(current.id)+'"></a><figcaption>Actual photo + text test · attempt '+current.revision+'</figcaption></figure></div><p class="finding">'+esc(current.notes)+'</p><fieldset class="information"><legend>Your information</legend><div class="fields">'+fields+'</div><button id="update">Update prompt</button></fieldset><p class="prompt-help">Update the fields, then edit any additional wording or timetable rows in the full prompt. Keep the layout instructions. The test used the default information shown here; change the sample date before posting a new event.</p><div class="prompt-tools"><button id="copy-prompt">Copy full prompt</button><a href="prompt-kit/prompts/'+esc(current.id)+'.txt" download>Download template</a></div><label for="full-prompt">Full image-generation prompt</label><textarea id="full-prompt" spellcheck="false"></textarea><p id="prompt-status" class="prompt-status" role="status"></p>';
 q('#update').onclick=fillPrompt;q('#copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText(q('#full-prompt').value);q('#prompt-status').textContent='Full prompt copied. Upload one normal photo with it.'}catch(e){q('#full-prompt').focus();q('#full-prompt').select();q('#prompt-status').textContent='Select and copy the full prompt above.'}};fillPrompt();}
q('#poster').onchange=render;
fetch('prompt-kit/prompts.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{catalog=data;q('#poster').innerHTML=data.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.id)+' · '+esc(p.style)+'</option>').join('');let id=location.hash.slice(1);if(catalog.some(p=>p.id===id))q('#poster').value=id;render()}).catch(()=>q('#chosen').textContent='The prompts could not load. Please refresh.');
