const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ids=DATA.shots.map(s=>s.id),key='venture-action-qc-v1'+(new URLSearchParams(location.search).has('test')?'-test':'');let state={items:{},name:'',overall:''};try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{}state.items||={};
const groupName=id=>DATA.groups.find(g=>g.id===id)?.title||id;const entry=id=>state.items[id]||{};const group=s=>entry(s.id).group||s.group;function verdict(id){const x=entry(id);return x.note?.trim()&&x.verdict!=='X'?'F':x.verdict||'-'}
const hash=new URLSearchParams(location.hash.slice(1)).get('r');if(hash&&hash.length===ids.length&&/^[KFX-]+$/.test(hash))ids.forEach((id,i)=>{state.items[id]||={};state.items[id].verdict=hash[i]});
function save(){localStorage.setItem(key,JSON.stringify(state));history.replaceState(null,'','#r='+ids.map(verdict).join(''));count()}
function count(){$('#count').textContent=ids.filter(id=>verdict(id)!=='-').length+' / '+ids.length+' reviewed'}
function card(s){const x=entry(s.id);return `<article class="card" id="${s.id}"><video controls playsinline loop preload="none" poster="${esc(s.poster)}" src="${esc(s.video)}" aria-label="${s.id}"></video><div class="body"><small>${s.id} · ${s.reference}</small><p>${esc(s.label)}</p><div class="votes">${[['K','Keep'],['F','Flag'],['X','Kill']].map(([v,l])=>`<button data-id="${s.id}" data-vote="${v}" aria-pressed="${verdict(s.id)===v}">${l}</button>`).join('')}</div><label>Notes<textarea data-note="${s.id}" placeholder="Change this grouping…">${esc(x.note||'')}</textarea></label><label>Action group<select data-group="${s.id}">${DATA.groups.map(g=>`<option value="${g.id}" ${group(s)===g.id?'selected':''}>${esc(g.title)}</option>`).join('')}</select></label><div class="links"><a href="${esc(s.full)}" target="_blank">Full reference ↗</a><a href="${esc(s.source)}" target="_blank" rel="noopener">Original URL ↗</a></div></div></article>`}
function render(){const filter=$('#filter').value;$('#board').innerHTML=DATA.groups.filter(g=>!filter||g.id===filter).map((g,n)=>{const shots=DATA.shots.filter(s=>group(s)===g.id);if(!shots.length)return '';return `<section><div class="group-title"><h2>${DATA.groups.indexOf(g)+1}. ${esc(g.title)}</h2><p>${esc(g.note)}</p><span class="reviewed">${shots.length} clips</span></div>${['High angle','Mid angle','Low angle','Close-up','Split screen'].map(a=>{const sub=shots.filter(s=>s.angle===a);return sub.length?`<h3 class="angle">${a}</h3><div class="grid">${sub.map(card).join('')}</div>`:''}).join('')}</section>`}).join('');count()}
$('#filter').insertAdjacentHTML('beforeend',DATA.groups.map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join(''));$('#filter').onchange=render;
function buttons(id){document.querySelectorAll(`[data-id="${id}"][data-vote]`).forEach(b=>b.setAttribute('aria-pressed',verdict(id)===b.dataset.vote))}
$('#board').addEventListener('click',e=>{const b=e.target.closest('[data-vote]');if(!b)return;const id=b.dataset.id;state.items[id]||={};state.items[id].verdict=entry(id).verdict===b.dataset.vote?'-':b.dataset.vote;save();buttons(id)});
$('#board').addEventListener('input',e=>{const id=e.target.dataset.note;if(!id)return;state.items[id]||={};state.items[id].note=e.target.value;save();buttons(id)});
$('#board').addEventListener('change',e=>{const id=e.target.dataset.group;if(!id)return;state.items[id]||={};state.items[id].group=e.target.value;state.items[id].verdict='F';save();render();$('#status').textContent=id+' moved to '+groupName(e.target.value);document.getElementById(id)?.scrollIntoView({block:'center'})});
for(const field of ['overall','name']){$('#'+field).value=state[field];$('#'+field).oninput=e=>{state[field]=e.target.value;save()}}
function record(){return {name:state.name.trim()||'Anonymous',ts:new Date().toISOString(),ids,answers:ids.map(verdict).join(''),items:DATA.shots.map(s=>({id:s.id,angle:s.angle,proposed:s.group,group:group(s),verdict:verdict(s.id),note:entry(s.id).note||''})),overall:state.overall}}
function answerText(){const r=record();return ['Venture / Shot category QC',r.name,...r.items.map(x=>`${x.id}: ${x.verdict} | ${groupName(x.group)} | ${x.angle}${x.note?' | '+x.note:''}`),'Overall: '+r.overall,location.href].join('\n')}
$('#copy').onclick=async()=>{const t=answerText();try{await navigator.clipboard.writeText(t);$('#status').textContent='Copied.'}catch{$('#fallback').hidden=false;$('#fallback').value=t;$('#fallback').select();$('#status').textContent='Select and copy the answers above.'}};
$('#send').onclick=async()=>{const b=$('#send');b.disabled=true;$('#status').textContent='Sending…';try{let r=await fetch(STORE+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Could not read saved answers.');const d=await r.json();if(!Array.isArray(d.submissions))throw Error('Answer store unavailable.');const rec=record();d.submissions=d.submissions.filter(s=>(s.name||'').trim().toLowerCase()!==rec.name.toLowerCase());d.submissions.push(rec);r=await fetch(STORE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw Error('Send failed. Please retry.');$('#status').textContent='Answers sent.'}catch(e){$('#status').textContent=e.message+' Your changes are saved on this device.'}finally{b.disabled=false}};
document.addEventListener('play',e=>{if(e.target.tagName==='VIDEO')document.querySelectorAll('video').forEach(v=>{if(v!==e.target)v.pause()})},true);render();save();
