const modes=[['Fresh thinking. From the inside out.','A new approach to the meals you make every day.'],['Less fuss. All the flavour.','Let fresh ingredients do the talking.'],['Made for your everyday.','From a quick lunch to a table full of people.']];
const hero=document.querySelector('.hero');
document.querySelectorAll('.benefit-choice').forEach(button=>button.addEventListener('click',()=>{const index=Number(button.dataset.mode);hero.dataset.mode=index;document.querySelectorAll('.benefit-choice').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});document.querySelector('#mode-count').textContent=`0${index+1} / 03`;document.querySelector('#mode-title').textContent=modes[index][0];document.querySelector('#mode-copy').textContent=modes[index][1]}));
document.querySelector('.motion-toggle').addEventListener('click',e=>{const paused=document.body.classList.toggle('paused');e.currentTarget.setAttribute('aria-pressed',String(paused));e.currentTarget.innerHTML=paused?'Play motion <span aria-hidden="true">▷</span>':'Pause motion <span aria-hidden="true">Ⅱ</span>';e.currentTarget.setAttribute('aria-label',paused?'Play animations':'Pause animations')});
const menu=document.querySelector('.menu-button');menu.addEventListener('click',()=>{const open=document.querySelector('.site-header nav').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});document.querySelectorAll('.site-header nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.site-header nav').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation')}));
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
if(!reducedMotion.matches){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
const dialog=document.querySelector('#booking-dialog');let dialogTrigger;
document.querySelectorAll('.book-button').forEach(button=>button.addEventListener('click',()=>{dialogTrigger=button;document.querySelector('.site-header nav').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');dialog.showModal();document.body.style.overflow='hidden'}));
function closeDialog(){dialog.close();document.body.style.overflow='';(dialogTrigger?.offsetParent ? dialogTrigger : menu).focus()}
document.querySelector('.dialog-close').addEventListener('click',closeDialog);dialog.addEventListener('cancel',()=>{document.body.style.overflow=''});dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeDialog()}});
document.querySelector('#booking-form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.target);document.querySelector('#enquiry-summary').textContent=`${String(form.get('name')).trim()}, you’re interested in ${String(form.get('interest')).toLowerCase()}. Your reply address would be ${String(form.get('email')).trim()}.`;document.querySelector('#booking-form-view').hidden=true;document.querySelector('#booking-result').hidden=false;document.querySelector('#edit-enquiry').focus()});document.querySelector('#edit-enquiry').addEventListener('click',()=>{document.querySelector('#booking-result').hidden=true;document.querySelector('#booking-form-view').hidden=false;document.querySelector('#enquiry-name').focus()});
document.querySelectorAll('.feature-list details').forEach(detail=>detail.addEventListener('toggle',()=>{if(detail.open)document.querySelectorAll('.feature-list details').forEach(other=>{if(other!==detail)other.open=false})}));
const choices=[...document.querySelectorAll('.benefit-choice')];choices.forEach((choice,index)=>choice.addEventListener('keydown',event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();const next=(index+(event.key==='ArrowRight'?1:-1)+choices.length)%choices.length;choices[next].focus();choices[next].click()}}));

// Close the phone menu without losing keyboard focus.
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){document.querySelector('.site-header nav').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.focus()}});
